################################################################################
# ðŸ§º LAUNDRY ROOM AUTOMATION PACKAGE v1.1 - FINAL REFACTOR
# Author: Frank S Elaschat
# Updated: 2025-08-30
# Status: âœ… Finalized with diagnostics, instant-on, and restart protection.
################################################################################

input_boolean:
  laundry_motion_automation:
    name: "Laundry Room Motion Automation"
    icon: mdi:motion-sensor
    initial: true
  laundry_adaptive_override:
    name: "Laundry Room Adaptive Override"
    icon: mdi:tune
    initial: false

input_number:
  laundry_motion_timeout:
    name: "Laundry Motion Timeout"
    min: 15
    max: 300
    step: 15
    initial: 30
    unit_of_measurement: "seconds"
    icon: mdi:timer
  laundry_override_brightness:
    name: "Laundry Room Override Brightness"
    min: 30
    max: 100
    step: 10
    initial: 80
    unit_of_measurement: "%"
    icon: mdi:brightness-7
  laundry_fallback_day_brightness:
    name: "Laundry Day Fallback Brightness"
    min: 40
    max: 100
    step: 5
    initial: 80
    unit_of_measurement: "%"
    icon: mdi:brightness-6
  laundry_fallback_evening_brightness:
    name: "Laundry Evening Fallback Brightness"
    min: 30
    max: 80
    step: 5
    initial: 60
    unit_of_measurement: "%"
    icon: mdi:brightness-4
  laundry_fallback_night_brightness:
    name: "Laundry Night Fallback Brightness"
    min: 1
    max: 10
    step: 1
    initial: 1
    unit_of_measurement: "%"
    icon: mdi:brightness-2

template:
  - sensor:
      - name: "Laundry Room Target Brightness"
        unique_id: laundry_room_brightness_main_v2
        unit_of_measurement: "%"
        state: >-
          {% set use_pyscript = is_state('input_boolean.all_rooms_use_pyscript', 'on') %}
          {% set home_mode = states('input_select.home_state') %}
          {% set override_active = is_state('input_boolean.laundry_adaptive_override', 'on') %}
          
          {% if override_active %}
            {{ states('input_number.laundry_override_brightness') | int(80) }}
          {% elif home_mode == 'Night' %}
            {{ states('input_number.laundry_fallback_night_brightness') | int(1) }}
          {% elif is_state('input_boolean.adaptive_learning_enabled', 'on') and state_attr('sensor.learned_brightness_laundry', 'using_learned') %}
            {{ states('sensor.learned_brightness_laundry') | int(60) }}
          {% elif use_pyscript and states('pyscript.test_laundry_brightness') not in ['unknown', 'unavailable'] %}
            {{ states('pyscript.test_laundry_brightness') | int(60) }}
          {% elif is_state('input_boolean.intelligent_lighting_enable', 'on') %}
            {{ states('sensor.intelligent_brightness_laundry') | int(60) }}
          {% else %}
            {% if home_mode in ['Evening', 'Early Morning'] %}
              {{ states('input_number.laundry_fallback_evening_brightness') | int(60) }}
            {% elif home_mode == 'Day' %}
              {{ states('input_number.laundry_fallback_day_brightness') | int(80) }}
            {% else %}
              60
            {% endif %}
          {% endif %}
        attributes:
          calculation_source: >
            {% set use_pyscript = is_state('input_boolean.all_rooms_use_pyscript', 'on') %}
            {% set override_active = is_state('input_boolean.laundry_adaptive_override', 'on') %}
            {% set home_mode = states('input_select.home_state') %}

            {% if override_active %} Manual Override
            {% elif home_mode == 'Night' %} Night Mode Lock
            {% elif is_state('input_boolean.adaptive_learning_enabled', 'on') and state_attr('sensor.learned_brightness_laundry', 'using_learned') %} Adaptive Learning
            {% elif use_pyscript and states('pyscript.test_laundry_brightness') not in ['unknown', 'unavailable'] %} PyScript Engine
            {% elif is_state('input_boolean.intelligent_lighting_enable', 'on') %} Intelligent System
            {% else %} Fallback Values
            {% endif %}
          confirmations: "{{ state_attr('sensor.learned_brightness_laundry', 'confirmations') | int(0) }}"

      - name: "Laundry Room ALS Status"
        state: >-
          {% set enabled = is_state('input_boolean.laundry_motion_automation', 'on') %}
          {% set motion = is_state('binary_sensor.laundry_iris_occupancy', 'on') %}
          {% set brightness = states('sensor.laundry_room_target_brightness') | int(0) %}
          {% set source = state_attr('sensor.laundry_room_target_brightness', 'calculation_source') %}
          {% set home_mode = states('input_select.home_state') %}
          {% set error = states('input_text.als_error_laundry') %}
          {% if error not in ['', 'unknown', 'unavailable'] %} ðŸš« Error Present
          {% elif not enabled %} â¸ï¸ System Disabled
          {% elif home_mode == 'Away' %} ðŸšª Away Mode
          {% elif motion %} ðŸ’¡ Motion Active ({{ brightness }}%)
          {% else %} ðŸ§º Ready ({{ source }})
          {% endif %}
        icon: >-
          {% set status = this.state %}
          {% if 'ðŸš«' in status %} mdi:alert-circle
          {% elif 'â¸ï¸' in status %} mdi:pause-circle
          {% elif 'ðŸšª' in status %} mdi:home-export-outline
          {% elif 'ðŸ’¡' in status %} mdi:lightbulb-on
          {% else %} mdi:washing-machine
          {% endif %}

automation:
  - id: laundry_motion_lights
    alias: "Laundry Room - Motion Lights"
    description: "Motion-triggered lighting with adaptive/intelligent brightness control"
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.laundry_iris_occupancy
        to: "on"
    conditions:
      - condition: state
        entity_id: input_boolean.laundry_motion_automation
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_state
            state: "Away"
      - condition: template
        value_template: >
          {{ trigger.from_state is not none and
              trigger.from_state.state not in ['unknown', 'unavailable'] }}
    actions:
      - action: light.turn_on
        target:
          entity_id: light.laundry_room
        data:
          brightness_pct: "{{ states('sensor.laundry_room_target_brightness') | int }}"

  - id: laundry_motion_off
    alias: "Laundry Room - Motion Off"
    description: "Turns off laundry lights after motion timeout"
    mode: restart
    triggers:
      - trigger: state
        entity_id: binary_sensor.laundry_iris_occupancy
        to: "off"
        for:
          seconds: "{{ states('input_number.laundry_motion_timeout') | int(30) }}"
    conditions:
      - condition: state
        entity_id: input_boolean.laundry_motion_automation
        state: "on"
      - condition: state
        entity_id: light.laundry_room
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.home_state
            state: "Away"
    actions:
      - action: light.turn_off
        target:
          entity_id: light.laundry_room
        data:
          transition: 3

  - id: laundry_mode_transitions
    alias: "Laundry Room - Mode Transitions"
    description: "Handles lighting changes when home mode changes"
    mode: restart
    triggers:
      - trigger: state
        entity_id: input_select.home_state
    actions:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'Away' }}"
            sequence:
              - action: light.turn_off
                target:
                  entity_id: light.laundry_room
          - conditions: "{{ trigger.to_state.state == 'Night' and is_state('light.laundry_room', 'on') }}"
            sequence:
              - action: light.turn_on
                target:
                  entity_id: light.laundry_room
                data:
                  brightness_pct: "{{ states('sensor.laundry_room_target_brightness') | int }}"
                  transition: 5

script:
  laundry_manual_override:
    alias: "Laundry Room Manual Override"
    sequence:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.laundry_adaptive_override
      - action: light.turn_on
        target:
          entity_id: light.laundry_room
        data:
          brightness_pct: "{{ states('input_number.laundry_override_brightness') | int }}"

  laundry_clear_override:
    alias: "Laundry Room Clear Override"
    sequence:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.laundry_adaptive_override